table Geography
	lineageTag: 822fe0ae-ccdb-41e1-96fd-5fe140df10f4

	column geography_sk
		dataType: string
		lineageTag: 763fc075-a55e-4d9a-84f6-d29030b8df2d
		summarizeBy: none
		sourceColumn: geography_sk

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 3ea7df8f-dcc9-4504-81aa-6113e046efe8
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: ccd25877-4cea-45d9-97ab-a1d3a4e3d92a
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column zip_code_prefix
		dataType: string
		lineageTag: 08d71b3e-f299-4036-beb0-764149f947dd
		summarizeBy: none
		sourceColumn: zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: a37bff81-b15b-42e6-b04b-c51e0201ef73
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 123bebdc-671b-41cf-b4d7-ee3a5ff78ca0
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Geography = m
		mode: import
		source =
				let
				  Source = DuckDB.Contents("C:\Users\Petya\Documents\Analytics Engineering\ecommerce-analytics-engineering\duckdb\olist.duckdb", "localhost", true, null, null, []),
				  #"Navigation 1" = Source{[Item = "dim_geography", Schema = "main", Catalog = "olist"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Navigation 1",{{"state", "State"}})
				in
				  #"Renamed Columns"

	changedProperty = Name

